/*
 * Created on 11.05.2005
 * 
 * Copyright BMSTU 2005
 */
package ru.bmstu.iu5.opsk.path;

import org.eclipse.jface.viewers.ISelectionProvider;
import org.eclipse.ui.part.IPage;

import ru.bmstu.iu5.opsk.views.ShortestPathView;

/**
 * An interface for shortest path page generated by network
 * model editor
 * 
 * @author Egorova Olga
 */
public interface IShortestPathPage extends IPage, ISelectionProvider {
	
	public abstract void setView(ShortestPathView view);

}
